# Generated by Django 6.0.4 on 2026-05-06 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0004_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=30)),
                ('variant_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variant_stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='productmanagement.product')),
            ],
            options={
                'unique_together': {('product', 'size', 'color')},
            },
        ),
    ]
