# Generated by Django 6.0.4 on 2026-05-09 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0007_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
