# Generated by Django 6.0.4 on 2026-05-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0009_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantimage',
            name='position',
            field=models.IntegerField(default=1, verbose_name='defualt=0'),
            preserve_default=False,
        ),
    ]
