# Generated by Django 6.0.4 on 2026-05-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0010_productvariantimage_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantimage',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
