# Generated by Django 6.0.4 on 2026-05-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0011_alter_productvariantimage_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantimage',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
