# Generated by Django 6.0.4 on 2026-06-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
                ('house_name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('area', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=30)),
                ('address_type', models.CharField(max_length=30)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
