# Generated by Django 6.0.4 on 2026-04-26 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='type',
            new_name='address_type',
        ),
    ]
