# Generated by Django 6.0.4 on 2026-04-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_alter_address_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='area',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='house_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.CharField(max_length=30),
        ),
    ]
