# Generated by Django 6.0.4 on 2026-05-30 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_referral_code_customuser_referred_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='expired_at',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='is_used',
        ),
    ]
