# Generated by Django 6.0.4 on 2026-07-21 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderaddress_alter_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
    ]
